name: CI
on:
  schedule:
    - cron: '30 5 * * *'

  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  changes:
    # Disable the filter on scheduled runs because we don't want to skip those
    if: github.event_name != 'schedule'
    continue-on-error: true # Makes sure errors won't stop us
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      # For PRs the path filter check with Github API, so no need to checkout
      # for them.
      - if: github.event_name != 'pull_request'
        name: Checkout (if not PR)
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - '**.cfg'
              - '**.nims'
              - '**.nim'
              - '**.nimble'
              - 'tests/**'
              - '.github/workflows/ci.yml'

  build:
    # Build if the files we care about are changed.
    needs: changes
    # Make sure to always run regardless of whether the filter success or not.
    # When the filter fails there won't be an output, so checking for `false`
    # state is better than checking for `true`.
    #
    # The always() function here is required for the job to always run despite
    # what Github docs said, see: https://github.com/actions/runner/issues/491
    if: always() && !cancelled() && needs.changes.outputs.src != 'false'

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        nim: ['devel', 'version-1-6', 'version-1-4', 'version-1-2']
    name: '${{ matrix.os }} (${{ matrix.nim }})'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: project

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: ${{ matrix.nim }}

      - name: Run tests
        shell: bash
        run: |
          cd project
          git fetch --unshallow
          nimble --accept develop
          nimble --accept install "https://github.com/disruptek/balls"
          git clone --depth 1 --branch v1.3.0 https://github.com/libgit2/libgit2.git
          cd libgit2
          mkdir build
          cd build
          cmake ..
          cmake --build . -- --quiet
          cd ../..
          nimble -y develop
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            balls --backend:c --backend:cpp --mm:arc --mm:orc -d:libgit2Lib="$(pwd)/libgit2/build/libgit2.dylib" --passc:"-I$(pwd)/libgit2/include"
          else
            balls --backend:c --backend:cpp --mm:arc --mm:orc -d:libgit2Lib="$(pwd)/libgit2/build/libgit2.so" --passc:"-I$(pwd)/libgit2/include"
          fi

      - name: Build docs
        if: ${{ matrix.docs }} == 'true'
        shell: bash
        run: |
          cd project
          branch=${{ github.ref }}
          branch=${branch##*/}
          nimble doc --project --outdir:docs --path="." \
            '--git.url:https://github.com/${{ github.repository }}' \
            '--git.commit:${{ github.sha }}' \
            "--git.devel:$branch" \
            gittyup.nim
          # Ignore failures for older Nim
          cp docs/{the,}index.html || true

      - name: Publish docs
        if: >
          github.event_name == 'push' && github.ref == 'refs/heads/master' &&
          matrix.os == 'ubuntu-latest' && matrix.nim == 'devel'
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: project/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Set check-required on this
  success:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    name: 'All check passes'
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        name: 'Fail when previous jobs fails'
        run: |
          echo "::error::One of the previous jobs failed"
          exit 1
